// Country dataset: ISO 3166-1 alpha-2 code (matches flag-icons CSS classes) + name.
// `alts` are accepted alternate spellings/names for the "type the name" mode.
const COUNTRIES = [
  // Africa
  { code: "dz", name: "Algeria" },
  { code: "ao", name: "Angola" },
  { code: "bj", name: "Benin" },
  { code: "bw", name: "Botswana" },
  { code: "bf", name: "Burkina Faso" },
  { code: "bi", name: "Burundi" },
  { code: "cv", name: "Cabo Verde", alts: ["cape verde"] },
  { code: "cm", name: "Cameroon" },
  { code: "cf", name: "Central African Republic", alts: ["car"] },
  { code: "td", name: "Chad" },
  { code: "km", name: "Comoros" },
  { code: "cg", name: "Republic of the Congo", alts: ["congo", "congo republic", "congo-brazzaville"] },
  { code: "cd", name: "DR Congo", alts: ["democratic republic of the congo", "congo-kinshasa", "dr congo", "drc"] },
  { code: "ci", name: "Ivory Coast", alts: ["cote d'ivoire", "cote divoire", "ivory coast"] },
  { code: "dj", name: "Djibouti" },
  { code: "eg", name: "Egypt" },
  { code: "gq", name: "Equatorial Guinea" },
  { code: "er", name: "Eritrea" },
  { code: "sz", name: "Eswatini", alts: ["swaziland"] },
  { code: "et", name: "Ethiopia" },
  { code: "ga", name: "Gabon" },
  { code: "gm", name: "Gambia" },
  { code: "gh", name: "Ghana" },
  { code: "gn", name: "Guinea" },
  { code: "gw", name: "Guinea-Bissau" },
  { code: "ke", name: "Kenya" },
  { code: "ls", name: "Lesotho" },
  { code: "lr", name: "Liberia" },
  { code: "ly", name: "Libya" },
  { code: "mg", name: "Madagascar" },
  { code: "mw", name: "Malawi" },
  { code: "ml", name: "Mali" },
  { code: "mr", name: "Mauritania" },
  { code: "mu", name: "Mauritius" },
  { code: "ma", name: "Morocco" },
  { code: "mz", name: "Mozambique" },
  { code: "na", name: "Namibia" },
  { code: "ne", name: "Niger" },
  { code: "ng", name: "Nigeria" },
  { code: "rw", name: "Rwanda" },
  { code: "st", name: "Sao Tome and Principe" },
  { code: "sn", name: "Senegal" },
  { code: "sc", name: "Seychelles" },
  { code: "sl", name: "Sierra Leone" },
  { code: "so", name: "Somalia" },
  { code: "za", name: "South Africa" },
  { code: "ss", name: "South Sudan" },
  { code: "sd", name: "Sudan" },
  { code: "tz", name: "Tanzania" },
  { code: "tg", name: "Togo" },
  { code: "tn", name: "Tunisia" },
  { code: "ug", name: "Uganda" },
  { code: "zm", name: "Zambia" },
  { code: "zw", name: "Zimbabwe" },
 
  // Asia
  { code: "af", name: "Afghanistan" },
  { code: "am", name: "Armenia" },
  { code: "az", name: "Azerbaijan" },
  { code: "bh", name: "Bahrain" },
  { code: "bd", name: "Bangladesh" },
  { code: "bt", name: "Bhutan" },
  { code: "bn", name: "Brunei" },
  { code: "kh", name: "Cambodia" },
  { code: "cn", name: "China" },
  { code: "cy", name: "Cyprus" },
  { code: "ge", name: "Georgia" },
  { code: "in", name: "India" },
  { code: "id", name: "Indonesia" },
  { code: "ir", name: "Iran" },
  { code: "iq", name: "Iraq" },
  { code: "il", name: "Israel" },
  { code: "jp", name: "Japan" },
  { code: "jo", name: "Jordan" },
  { code: "kz", name: "Kazakhstan" },
  { code: "kw", name: "Kuwait" },
  { code: "kg", name: "Kyrgyzstan" },
  { code: "la", name: "Laos" },
  { code: "lb", name: "Lebanon" },
  { code: "my", name: "Malaysia" },
  { code: "mv", name: "Maldives" },
  { code: "mn", name: "Mongolia" },
  { code: "mm", name: "Myanmar", alts: ["burma"] },
  { code: "np", name: "Nepal" },
  { code: "kp", name: "North Korea" },
  { code: "om", name: "Oman" },
  { code: "pk", name: "Pakistan" },
  { code: "ps", name: "Palestine" },
  { code: "ph", name: "Philippines" },
  { code: "qa", name: "Qatar" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "sg", name: "Singapore" },
  { code: "kr", name: "South Korea" },
  { code: "lk", name: "Sri Lanka" },
  { code: "sy", name: "Syria" },
  { code: "tw", name: "Taiwan" },
  { code: "tj", name: "Tajikistan" },
  { code: "th", name: "Thailand" },
  { code: "tl", name: "Timor-Leste", alts: ["east timor"] },
  { code: "tr", name: "Turkey", alts: ["turkiye"] },
  { code: "tm", name: "Turkmenistan" },
  { code: "ae", name: "United Arab Emirates", alts: ["uae"] },
  { code: "uz", name: "Uzbekistan" },
  { code: "vn", name: "Vietnam" },
  { code: "ye", name: "Yemen" },
 
  // Europe
  { code: "al", name: "Albania" },
  { code: "ad", name: "Andorra" },
  { code: "at", name: "Austria" },
  { code: "by", name: "Belarus" },
  { code: "be", name: "Belgium" },
  { code: "ba", name: "Bosnia and Herzegovina", alts: ["bosnia"] },
  { code: "bg", name: "Bulgaria" },
  { code: "hr", name: "Croatia" },
  { code: "cz", name: "Czechia", alts: ["czech republic"] },
  { code: "dk", name: "Denmark" },
  { code: "ee", name: "Estonia" },
  { code: "fi", name: "Finland" },
  { code: "fr", name: "France" },
  { code: "de", name: "Germany" },
  { code: "gr", name: "Greece" },
  { code: "hu", name: "Hungary" },
  { code: "is", name: "Iceland" },
  { code: "ie", name: "Ireland" },
  { code: "it", name: "Italy" },
  { code: "xk", name: "Kosovo" },
  { code: "lv", name: "Latvia" },
  { code: "li", name: "Liechtenstein" },
  { code: "lt", name: "Lithuania" },
  { code: "lu", name: "Luxembourg" },
  { code: "mt", name: "Malta" },
  { code: "md", name: "Moldova" },
  { code: "mc", name: "Monaco" },
  { code: "me", name: "Montenegro" },
  { code: "nl", name: "Netherlands" },
  { code: "mk", name: "North Macedonia", alts: ["macedonia"] },
  { code: "no", name: "Norway" },
  { code: "pl", name: "Poland" },
  { code: "pt", name: "Portugal" },
  { code: "ro", name: "Romania" },
  { code: "ru", name: "Russia" },
  { code: "sm", name: "San Marino" },
  { code: "rs", name: "Serbia" },
  { code: "sk", name: "Slovakia" },
  { code: "si", name: "Slovenia" },
  { code: "es", name: "Spain" },
  { code: "se", name: "Sweden" },
  { code: "ch", name: "Switzerland" },
  { code: "ua", name: "Ukraine" },
  { code: "gb", name: "United Kingdom", alts: ["uk", "britain", "great britain"] },
  { code: "va", name: "Vatican City", alts: ["holy see", "vatican"] },
 
  // North America
  { code: "ag", name: "Antigua and Barbuda" },
  { code: "bs", name: "Bahamas" },
  { code: "bb", name: "Barbados" },
  { code: "bz", name: "Belize" },
  { code: "ca", name: "Canada" },
  { code: "cr", name: "Costa Rica" },
  { code: "cu", name: "Cuba" },
  { code: "dm", name: "Dominica" },
  { code: "do", name: "Dominican Republic" },
  { code: "sv", name: "El Salvador" },
  { code: "gd", name: "Grenada" },
  { code: "gt", name: "Guatemala" },
  { code: "ht", name: "Haiti" },
  { code: "hn", name: "Honduras" },
  { code: "jm", name: "Jamaica" },
  { code: "mx", name: "Mexico" },
  { code: "ni", name: "Nicaragua" },
  { code: "pa", name: "Panama" },
  { code: "kn", name: "Saint Kitts and Nevis" },
  { code: "lc", name: "Saint Lucia" },
  { code: "vc", name: "Saint Vincent and the Grenadines" },
  { code: "tt", name: "Trinidad and Tobago" },
  { code: "us", name: "United States", alts: ["usa", "united states of america", "america"] },
 
  // South America
  { code: "ar", name: "Argentina" },
  { code: "bo", name: "Bolivia" },
  { code: "br", name: "Brazil" },
  { code: "cl", name: "Chile" },
  { code: "co", name: "Colombia" },
  { code: "ec", name: "Ecuador" },
  { code: "gy", name: "Guyana" },
  { code: "py", name: "Paraguay" },
  { code: "pe", name: "Peru" },
  { code: "sr", name: "Suriname" },
  { code: "uy", name: "Uruguay" },
  { code: "ve", name: "Venezuela" },
 
  // Oceania
  { code: "au", name: "Australia" },
  { code: "fj", name: "Fiji" },
  { code: "ki", name: "Kiribati" },
  { code: "mh", name: "Marshall Islands" },
  { code: "fm", name: "Micronesia" },
  { code: "nr", name: "Nauru" },
  { code: "nz", name: "New Zealand" },
  { code: "pw", name: "Palau" },
  { code: "pg", name: "Papua New Guinea" },
  { code: "ws", name: "Samoa" },
  { code: "sb", name: "Solomon Islands" },
  { code: "to", name: "Tonga" },
  { code: "tv", name: "Tuvalu" },
  { code: "vu", name: "Vanuatu" },
];
 
// Groups of flags that people commonly mix up — used to pick harder,
// more relevant wrong answers for multiple choice instead of pure random
// ones. A country can appear in more than one group. When there's more
// than 3 other members in a group, which 3 get used is randomized each
// time, so the same country doesn't always show the same distractors.
const CONFUSION_GROUPS = [
  ["ru", "sk", "si", "rs", "nl", "lu"], // white/blue/red horizontal tricolors
  ["no", "se", "dk", "fi", "is"], // Nordic crosses
  ["ml", "sn", "gn", "cm", "gh", "et"], // pan-African green/yellow/red family
  ["ie", "ci"], // Ireland vs Ivory Coast (mirrored)
  ["id", "mc", "pl"], // red/white two-tone flags
  ["td", "ro", "ad", "md"], // blue/yellow/red vertical tricolors
  ["au", "nz"], // Union Jack + Southern Cross
  ["co", "ec", "ve"], // yellow/blue/red horizontal (Gran Colombia)
  ["tr", "tn"], // red field, white crescent + star
  ["qa", "bh"], // maroon/red with serrated white edge
  ["ar", "uy"], // light blue/white with a sun
  ["mx", "it"], // green/white/red vertical
  ["hn", "sv", "ni"], // Central American blue/white/blue
];
 
 
